;;; ccc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ccc.el

(autoload 'ccc-setup "ccc")
(autoload 'ccc-update-buffer-local-frame-params "ccc" "\


(fn &optional BUFFER)")
(register-definition-prefixes "ccc" '("ccc-"))

;;; End of scraped data

(provide 'ccc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ccc-autoloads.el ends here
